name: Bug Report
description: Report a bug in the app
title: "[Bug]: "
labels: ["bug"]
assignees:
  - RJR-003
body:
  - type: dropdown
    id: affected-feats
    attributes:
      label: Under which feature did you identify the bug?
      options:
        - search
        - filter
        - add employee
        - edit employee
        - delete employee
        - Don't known / other
      multiple: true
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
